import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

// 카카오 스크립트 추가
import KakaoScript from "@/app/utils/kakaoScript";

// 카카오 로그인 버튼
import KakaoLoginButton from "@/app/components/KakaoLoginBtn";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <KakaoLoginButton />
        {children}

        <KakaoScript />
      </body>
    </html>
  );
}
